#示例配置信息

#其他配置文件,可以使用绝对路径
#或者相对于 anylink 二进制文件的路径

#数据文件
db_type = "sqlite3"
db_source = "./conf/anylink.db"
#证书文件
cert_file = "./conf/vpn_cert.pem"
cert_key = "./conf/vpn_cert.key"
files_path = "./conf/files"

#日志目录,默认为空写入标准输出
#log_path = "./log"
log_level = "info"

#系统名称
issuer = "Scu de SSLVPN"
#后台管理用户
admin_user = "shangkouyou"
#pass 123456
admin_pass = "$2a$10$5Z1AdsqtgOtHpNzy7nKpMe8Toa8TbXb7YVm2ZNnLKZ3HdSI6lXcha"
# 留空表示不开启 otp, 开启otp后密码为  pass + 6位otp
# 生成 ./anylink tool -o
admin_otp = ""
jwt_secret = "abcdef.0123456789.abcdef"
profile_name = "SSLVPN"

#登录单独验证OTP窗口
auth_alone_otp = true

#加密保存用户密码
encryption_password = true

#TCP服务监听地址(任意端口)
server_addr = ":443"
#开启 DTLS
server_dtls = false
#UDP监听地址(任意端口)
server_dtls_addr = ":443"
#后台服务监听地址
admin_addr = ":1024"

#最大客户端数量
max_client = 200
#单个用户同时在线数量
max_user_client = 3

#虚拟网络类型[tun macvtap]
link_mode = "tun"
#客户端分配的ip地址池
#docker环境一般默认 eth0，其他情况根据实际网卡信息填写
ipv4_master = "eth0"
ipv4_cidr = "10.21.13.0/24"
ipv4_gateway = "10.21.13.1"
ipv4_start = "10.21.13.100"
ipv4_end = "10.21.13.200"

#是否自动添加nat
iptables_nat = false

#客户端显示详细错误信息(线上环境慎开启)
display_error = true

# MTU 设置（非常关键）
Mtu = 1200